if(APPLE)
	set(CONFIG_CMD cmake -DCMAKE_INSTALL_PREFIX=${ETH_DEPENDENCY_INSTALL_DIR} -DCMAKE_MODULE_PATH:PATH=${CMAKE_CURRENT_SOURCE_DIR} -DETH_DEPENDENCY_INSTALL_DIR:PATH=${ETH_DEPENDENCY_INSTALL_DIR} -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -Wno-dev .)
else()
    set(CONFIG_CMD cmake -DCMAKE_INSTALL_PREFIX=${ETH_DEPENDENCY_INSTALL_DIR} -DCMAKE_MODULE_PATH:PATH=${CMAKE_CURRENT_SOURCE_DIR} -DETH_DEPENDENCY_INSTALL_DIR:PATH=${ETH_DEPENDENCY_INSTALL_DIR} -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST .)
endif()


# DO NOT CHANGE ANYTHING HERE!
ExternalProject_Add(json-cpp
    # DEPENDS curl # re-enable later, when we build curl again
	GIT_REPOSITORY https://github.com/open-source-parsers/jsoncpp.git
	BINARY_DIR jsoncpp-prefix/src/jsoncpp
    CONFIGURE_COMMAND ${CONFIG_CMD}
	BUILD_COMMAND make -j 3
	INSTALL_COMMAND make install
)
